USE [master]
GO

/****** Object:  Database [PDV_Wes]    Script Date: 17/08/2021 19:38:24 ******/
CREATE DATABASE [PDV_Wes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PDV_Wes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PDV_Wes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PDV_Wes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PDV_Wes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PDV_Wes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PDV_Wes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PDV_Wes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PDV_Wes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PDV_Wes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PDV_Wes] SET ARITHABORT OFF 
GO

ALTER DATABASE [PDV_Wes] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PDV_Wes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PDV_Wes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PDV_Wes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PDV_Wes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PDV_Wes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PDV_Wes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PDV_Wes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PDV_Wes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PDV_Wes] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PDV_Wes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PDV_Wes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PDV_Wes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PDV_Wes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PDV_Wes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PDV_Wes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PDV_Wes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PDV_Wes] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PDV_Wes] SET  MULTI_USER 
GO

ALTER DATABASE [PDV_Wes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PDV_Wes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PDV_Wes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PDV_Wes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PDV_Wes] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PDV_Wes] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PDV_Wes] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PDV_Wes] SET  READ_WRITE 
GO


